"""add player_invitations table

Revision ID: 1705ccface4a
Revises: 7a4c9e2d1f30
Create Date: 2026-07-03 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1705ccface4a'
down_revision = '7a4c9e2d1f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_invitations',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('invited_by_coach_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', 'expired', name='player_invitation_status'), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_invitations_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_invitations_token'))

    op.drop_table('player_invitations')
    # ### end Alembic commands ###
