"""add message reaction

Revision ID: 19358b6b74b1
Revises: b2c3d4e5f6a7
Create Date: 2026-03-09 17:51:09.249492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19358b6b74b1'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('push_subscriptions_user_id_key', type_='unique')

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_constraint('token_blocklist_jti_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_unique_constraint('token_blocklist_jti_key', ['jti'])

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_unique_constraint('push_subscriptions_user_id_key', ['user_id'])

    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
