"""add message type

Revision ID: 30dba1e0df17
Revises: b43995ce3dea
Create Date: 2026-03-11 12:54:14.938125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dba1e0df17'
down_revision = 'b43995ce3dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(), server_default='text', nullable=False))
        batch_op.add_column(sa.Column('msg_metadata', sa.JSON(), nullable=True))

    with op.batch_alter_table('notification_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_templates', sa.JSON(), nullable=True))

    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'messages', ['message_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('message_id')

    with op.batch_alter_table('notification_configs', schema=None) as batch_op:
        batch_op.drop_column('message_templates')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('msg_metadata')
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
