"""add coach_invitations table

Revision ID: 362d13470558
Revises: d4e5f6a7b8c9
Create Date: 2026-06-10 09:03:00.072715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '362d13470558'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_invitations',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('invited_by_coach_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', 'expired', name='coach_invitation_status'), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coach_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_invitations_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_invitations_token'))

    op.drop_table('coach_invitations')
    # ### end Alembic commands ###
