"""add notification functionalities

Revision ID: a20050262cd7
Revises: b3c4d5e6f7a8
Create Date: 2026-03-17 12:02:31.932171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20050262cd7'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_instance_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('original_player_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.Enum('left', 'right', name='vacancy_side'), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'filled', 'expired', name='vacancy_status'), nullable=False),
    sa.Column('current_round_number', sa.Integer(), nullable=False),
    sa.Column('current_batch_number', sa.Integer(), nullable=False),
    sa.Column('filled_by_player_id', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filled_by_player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_instance_id'], ['lesson_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['coach_levels.id'], ),
    sa.ForeignKeyConstraint(['original_player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiting_list_entries',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_instance_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_instance_id'], ['lesson_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_instance_id', 'player_id', name='uq_waiting_session_player')
    )
    with op.batch_alter_table('notification_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_timing', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('invitation_start_timing', sa.JSON(), nullable=True))

    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacancy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vacancies', ['vacancy_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vacancy_id')

    with op.batch_alter_table('notification_configs', schema=None) as batch_op:
        batch_op.drop_column('invitation_start_timing')
        batch_op.drop_column('reminder_timing')

    op.drop_table('waiting_list_entries')
    op.drop_table('vacancies')
    # ### end Alembic commands ###
