"""add notification for parent lesson

Revision ID: b43995ce3dea
Revises: c6f54b3fa846
Create Date: 2026-03-11 11:45:52.442862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43995ce3dea'
down_revision = 'c6f54b3fa846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), server_default='1', nullable=False))

    with op.batch_alter_table('notification_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_groups', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_configs', schema=None) as batch_op:
        batch_op.drop_column('notification_groups')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')

    # ### end Alembic commands ###
